# Generated by Django 3.2.17 on 2023-03-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='ext_info',
            field=models.CharField(default='{}', max_length=3200, verbose_name='扩展信息'),
        ),
    ]
