# Generated by Django 3.2.17 on 2023-03-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_alter_file_ext_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ident',
            field=models.UUIDField(default='a77ba65612524db3941b287e66b11fad', verbose_name='标识符'),
        ),
    ]
